CREATE TABLE conto(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saldo FLOAT
);


CREATE TABLE cliente(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128),
    password VARCHAR(128),
    idConto INTEGER,
    FOREIGN KEY(idConto) REFERENCES conto(id)
);


CREATE TABLE venditore(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128),
    password VARCHAR(128),
    idConto INTEGER,
    FOREIGN KEY(idConto) REFERENCES conto(id)
);

CREATE TABLE oggetto(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128),
    urlImmagine VARCHAR(128),
    descrizione VARCHAR(128),
    prezzo DOUBLE PRECISION,
    quantita INTEGER,
    idVenditore INTEGER,
    FOREIGN KEY(idVenditore) REFERENCES venditore(id)
);


/*Popolamento del DB*/
insert into conto (id, saldo)
values (default, 2250.0), (default, 150.0), (default, 3650.0), (default, 1200.0), (default, 500.0), (default, 450.0);


insert into cliente (id, username, password, idconto)
values (default, 'RossiMario', 'c1', 1), (default, 'MauroFrau', 'c2', 2), (default, 'AnnaFabiani', 'c3', 3);


insert into venditore (id, username, password, idconto)
values (default, 'NotaShop', 'v1', 4), (default, 'Music4All', 'v2', 5), (default, 'SweetNote', 'v3', 6);


insert into oggetto (id, nome, urlimmagine, descrizione, prezzo, quantita, idvenditore)
values (default, 'Fender Stratocaster Classic 50', 
                 'img/fender-classic-50s-stratocaster.jpg',
                 'Una chitarra', 500.0, 3, 1),

(default, 'Basso Fender Jazz', 'img/fenderJazz.jpg','Un basso', 700.0, 20, 1),
(default, 'Batteria Ludwig Classic Mapple', 'img/classicMapple.jpg','Una batteria', 1700.0, 32, 2),
(default, 'Tamaky Classica', 'img/tamaky.jpeg','Una chitarra classica', 15.0, 20, 1),
(default, 'Flauto Aulos', 'img/aulos.jpg','Un flauto', 10.50, 347, 3);

